### ISSUE TITLE
Rework content managers

### ISSUE THREAD

**Issue by ogizanagi** [Tom32i/content#11]
L'idée serait de permettre de les déclarer simplement depuis la config, sans code (sauf cas spécifiques) pour l'utilisateur:

```yaml
contents:
    App\Content\Model\Recipe:
        type: files
        path: content/recipes
    App\Content\Model\AnotherThingGDrive:
        type: gdrive
        url: ...
    App\Content\Model\AnotherThingFromDoctrine:
        type: doctrine
        table: ...
        columns_mapping: {...}
```

(pour l'instant on se concentre bien sûr uniquement sur des providers filesystem)

L'interface ContentProviderInterface deviendrait quelque chose dans ce genre:

```php
interface ContentProviderInterface
{
    /**
     * @return iterable<Content>
     */
    public function getContents(): iterable;

    public function getContent(string $slug): Content;

    public function supports(string $className): bool;
}

class Content {
    private string $slug;
    private \DateTime $lastModifiedTime;
    private \DateTime $createdAt;
    private string $rawContent;
    private string $format;
}
```

(l'intérêt de `Content` étant de s'abstraire complètement du filesystem tout en communiquant les infos dont on a besoin: slug/id, dates, contenu brut et type de contenu à décoder)

La première implem de `ContentProviderInterface` serait une implem local filesystem (`LocalFilesystemProvider`).

A voir jusqu'où on pousse l'utilisation du Finder et son exposition dans la config:

```yaml
contents:
   
    # Minimum config:
    App\Content\Model\Recipe:
        type: files
        path: content/recipes
    
    # Advanced config:
    App\Content\Model\Other:
        type: files
        path: content/other
        patterns: [*.md, *.yml]
        depth: 1 # null (no limit) by default?
        excludes: ['notThisFile.md', 'notThisSubdir/']
```

L'extension reçoit cette config et fourni type, classe supportée et config à une factory pour créer le service.

Le `ContentManager` reçoit ces contenus, et les decode en fonction de leur type.

--- 

A terme rien n'empêche même d'avoir plusieurs providers pour un même type:

```yaml
contents:
    App\Content\Model\Recipe:
        type: chain
        providers:
            - type: files
              path: content/recipes
            - type: gdrive
              url: ...
```
